### PR TITLE
Quick example

### PR DESCRIPTION
**Pull request by Thomzoy**
New class `QuickExample`.
This allows quick exploratory work:

```python
from edsnlp.viz import QuickExample

E = QuickExample(nlp)

text = """Le patient présente une nephropathie diabétique."""

E(text)
# Out:
```
```

                 Le patient présente une nephropathie diabétique.                  
                                                                                   
┏━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Entity                  ┃ Source   ┃ eds.negation ┃ eds.hypothesis ┃ eds.family ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ nephropathie            │ CKD      │ False        │ False          │ False      │
│ nephropathie diabétique │ diabetes │ False        │ False          │ False      │
└─────────────────────────┴──────────┴──────────────┴────────────────┴────────────┘
```

- [x] If this PR is a bug fix, the bug is documented in the test suite.
- [x] Changes were documented in the changelog (pending section).
- [x] If necessary, changes were made to the documentation (eg new pipeline).

### CODE REVIEW

**Comment by Thomzoy** [comment]
It's now available under `edsnlp.viz`
We might add other viz with `displacy` later !

**Comment by percevalw** [comment]
Great ! Might be worth adding an option to render as a dataframe later !

**Review by percevalw — DISMISSED** [review]
Changelog please !! :)

**Comment by Thomzoy** [comment]
> Great ! Might be worth adding an option to render as a dataframe later !

Done !

**Review by percevalw — APPROVED** [review]
Great thanks !

**Pull request merged**
