### PR TITLE
feat: allow Qualifiers to match on spangroups

### PR DESCRIPTION
**Pull request by Thomzoy**
## Description

Proposition for allowing `Qualifiers` to look for matches in sentences present in `doc.spans[key]`.
It would extend the current `on_ents_only` argument by adding another `on_spangroups` argument

Another way of doing this could be to be more general with, e.g. a `on` parameter that could be set to tell the Qualifiers to match on
- everything
- all entities
- entities present in spangroups
- entities present in a subset of spangoups

However, this approach would induce many API breaking changes, so maybe the first approach is preferable

## Checklist

- [x] If this PR is a bug fix, the bug is documented in the test suite.
- [x] Changes were documented in the changelog (pending section).
- [x] If necessary, changes were made to the documentation (eg new pipeline).

### CODE REVIEW

**Comment by Thomzoy** [comment]
Actualy some work was already done in the `dates` pipelines, so I took some inspiration from it

**Comment by Thomzoy** [comment]
Actualy some work was already done in the `dates` pipelines, so I took some inspiration from it

**Comment by Thomzoy** [comment]
Actualy some work was already done in the `dates` pipelines, so I took some inspiration from it

**Comment by Thomzoy** [comment]
Actualy some work was already done in the `dates` pipelines, so I took some inspiration from it

**Comment by percevalw** [comment]
Closing as this was merged in #213

**Pull request closed without merging**
