### PR TITLE
Fix behavior, disorder and qualifier pipes

### LINKED ISSUE #287: Include negation in tobacco and alcohol pipelines
With the current code, detailed status "ABSENT" is assigned only when negation is found after the entity, not before.

Example: 
If text is "Patient non fumeur", detailed_status is assigned to PRESENT.
If text is "Fumeur: non" , detailed_status is assigned to ABSENT.

Feature suggestion: 
The negation patterns from negation pipelines should be included to the tobacco/alcohol pipelines so detailed_status is set to ABSENT in any negation case.

### PR DESCRIPTION
**Pull request by Thomzoy**
## Description

Fix #287

This PR has two main goals:

1) Impove and simplify the behaviors and disorders pipes
2) To do so, add a `process` method to the `RuleBasedQualifier` that only returns qualified entities and token **without** actually tagging them (defering this task to the `__call__` method). This is useful when pipes need to use qualifier pipes internaly, but doesn't want to tag the original document.

### 1.1) Simplify the `status` attribute for disorder and behavior pipes

Currently, this `status` can take, for most disorder pipes, the values "PRESENT" or "ABSENT". I argue that:
* The "ABSENT" value is never used (it was in the behavior pipe, but see below)
* The "PRESENT" value isn't informative and can be misleading. For instance, "Tabac: 0" currently set `status` to "PRESENT" (and `_.negation` to True)

As such, we can simplify those and especialy remove this case with both "PRESENT" and "negation":
* By default, the `status` is set to None
* Instead of pipes setting `status` to "ABSENT", we now set `ent._.negation` to True and leave `status` to None

### 1.2) Fixing some issues with the alcohol and tobacco pipes, namely:
* Use the `NegationQualifier` to qualify the abstinence `status`, which we currently do directly with a basic regex
* As staed above, remove the use of `status="ABSENT"` in favor of using `ent._.negation`

⚠️ The negation pipe mentionned above will **only** be used to determine the abstinence status. As for any NER pipe, qualifiers should still be run after.

## 2)  Add a `process` method to the `RuleBasedQualifier`
As stated above the tobacco and alcohol pipes now use the `NegationQualifier` internaly. They both need to qualify the patient's abstience, which can be negated (e.g. "Patient fumeur non sevré") **but** without tagging the document. To this end (and as this use case may be more broad than those two pipes), we implemented a `process` method to the `RuleBasedQualifier` that only returns qualified entities and token **without** actually tagging them (defering this task to the `__call__` method).

## Checklist

- [x] If this PR is a bug fix, the bug is documented in the test suite.
- [x] Changes were documented in the changelog (pending section).
- [x] If necessary, changes were made to the documentation (eg new pipeline).

### CODE REVIEW

**Comment by Thomzoy** [comment]
TODO: update tests + mention all those changes clearly in the documentation

**Comment by Thomzoy** [comment]
As using negation inside the TobaccoMatcher required to run nlp(span) (so that the original document isn't tagged with `negation`), I propose an update on the RuleBasedQualifier by adding a `get_qualified` method which returns a typed dictionary with mandatory keys `tokens` and `ents`, each containing a list of tuples. For instance, 

```
# In qualifiers/base.py
class BaseQualifierResults(NamedTuple):
    tokens: List[NamedTuple]
    ents: List[NamedTuple]

# in negation.py
TokenNegationResults = namedtuple("TokenNegationResults", ["token", "negation"])
EntsNegationResults = namedtuple("TokenNegationResults", ["ent", "negation", "cues"])

class NegationResults(BaseQualifierResults):
    tokens: List[TokenNegationResults]
    ents: List[EntsNegationResults]
```

Most of the logic will be done in the `get_qualified` method, **but no tagging**.  
Tagging is still done in the `process` method, which calls `get_qualified`

@percevalw

**Comment by percevalw** [comment]
Many of our pipelines actually use the `process` method to extract entities and `__call__` to annotate on the document (ex with [`eds.dates`](https://github.com/aphp/edsnlp/blob/master/edsnlp/pipes/misc/dates/dates.py#L488-L507) or the generic [`eds.matcher`](https://github.com/aphp/edsnlp/blob/master/edsnlp/pipes/core/matcher/matcher.py#L173-L191)), maybe we could continue in this direction ? so tag in `__call__` and extract in `process`

**Comment by Thomzoy** [comment]
> Many of our pipelines actually use the `process` method to extract entities and `__call__` to annotate on the document (ex with [`eds.dates`](https://github.com/aphp/edsnlp/blob/master/edsnlp/pipes/misc/dates/dates.py#L488-L507) or the generic [`eds.matcher`](https://github.com/aphp/edsnlp/blob/master/edsnlp/pipes/core/matcher/matcher.py#L173-L191)), maybe we could continue in this direction ? so tag in `__call__` and extract in `process` @Thomzoy
> 
> For the output of the extraction step (`get_qualified` in your comment), maybe we can find a way to type hint `tokens` and `ents` ? otherwise I'm ok with it !

Fine with me ! For instance:  

In qualifiers/base
```python
@dataclass
class BaseTokenQualifierResults:
    token: Token


@dataclass
class BaseEntQualifierResults:
    ent: Span


@dataclass
class BaseQualifierResults:
    tokens: List[BaseTokenQualifierResults]
    ents: List[BaseEntQualifierResults]
```


In negation
```python
@dataclass
class TokenNegationResults(BaseTokenQualifierResults):
    # Single token
    negation: bool


@dataclass
class EntNegationResults(BaseEntQualifierResults):
    # Single entity
    negation: bool
    cues: List[Span]


@dataclass
class NegationResults(BaseQualifierResults):
    # All qualified tokens and entities
    tokens: List[TokenNegationResults]
    ents: List[EntNegationResults]
```

**Pull request merged**
